language: ruby

before_install:
  - export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
  - npm install

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2

sudo: false

script:
 - bundle exec rake test
 - script/test

gemfile:
  - Gemfile.rails32
  - Gemfile.rails40
  - Gemfile.rails41
  - Gemfile.rails42

